#!/usr/bin/env bash

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config border_width        1
bspc config window_gap          20

bspc monitor -d I II III IV V VI VII VIII IX X

# Visual options
# bspc config split_ratio         0.50
# bspc config borderless_monocle  true
# bspc config gapless_monocle     true
bspc config focus_follows_pointer false
# bspc config auto_alternate true
# bspc config auto_cancel true
bspc config normal_border_color "white"
bspc config active_border_color "red"
bspc config focused_border_color "red"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Steam state=floating follow=on
bspc rule -a Logisim state=floating follow=on
bspc rule -a Iceweasel follow=on

feh --bg-scale $HOME/Obrazy/debian-wallpaper.jpg
exec $HOME/.conky/run-conky.sh
sxhkd &
tint2 &
