#!/bin/bash

# using command "um" you can easily umount device
# e.g. um sdb1 sdb

cecho() {
  local code="\033["
  case "$1" in
    black  | bk) color="${code}0;30m";;
    red    |  r) color="${code}1;31m";;
    green  |  g) color="${code}1;32m";;
    yellow |  y) color="${code}1;33m";;
    blue   |  b) color="${code}1;34m";;
    purple |  p) color="${code}1;35m";;
    cyan   |  c) color="${code}1;36m";;
    gray   | gr) color="${code}0;37m";;
    *) local text="$1"
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  printf "$text"
}

DIR="/dev/dysk"

# if dir exists
if [ -d $DIR  ]; then
	# if dir isn't empty
	if [ "$(ls -A $DIR)"  ]; then 
		echo Unmounting...
	        cd $HOME
            	sudo udisksctl unmount -b /dev/$1
		sleep 3
            	sudo udisksctl power-off -b /dev/$2
	else
		echo "$DIR is empty"
	fi
else
	echo $DIR does not exist.
fi