#!/bin/bash
# Pacman Clean Script
#
# Colors
              blue="\033[1;34m"
              green="\033[1;32m"
              red="\033[1;31m"
              bold="\033[1;37m"
              reset="\033[0m"
              yellow="\033[1;33m"
              cyan="\033[1;36m"
             
# Check for root
     if [ $(whoami) != "root" ]; then
         echo -e $red"error:$reset you cannot perform this operation unless you are root."
         exit 1
fi
 
# Perform Clean
echo -e "$yellow    ==> $reset Cleaning unused packages "
pacman -Rs $(pacman -Qqdt)
echo -e "$cyan    ==> $reset Cleaning pacman cache"
pacman -Sc
echo -e "$blue    ==> $reset Cleaning complete "
exit 0
