#!/bin/bash

cecho() {
  local code="\033["
  case "$1" in
    black  | bk) color="${code}0;30m";;
    red    |  r) color="${code}1;31m";;
    green  |  g) color="${code}1;32m";;
    yellow |  y) color="${code}1;33m";;
    blue   |  b) color="${code}1;34m";;
    purple |  p) color="${code}1;35m";;
    cyan   |  c) color="${code}1;36m";;
    gray   | gr) color="${code}0;37m";;
    *) local text="$1"
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  printf "$text"
}

cecho r "=========================> Type your dev without number on the end:\n"
read -p "Your device is: /dev/" dev
sudo mkfs.ext4 /dev/$dev

cecho c "=========================> Type path to your .iso file:\n"
read -p "Where is .iso file: $HOME/" file
sudo dd if=$HOME/$file of=/dev/$dev bs=4k

cecho c "=========================> Unmounting /dev/$dev\n"
sync
umount /dev/$dev

cecho c "=========================> Done\n"
