#!/bin/bash

# using command "m arg" you can easily mount devices, for example:
# 1) ntfs devices: m -n sdb1
# 2) other devices: m sdb2
# Depends to mount ntfs device: fuse, ntfs-3g

cecho() {
  local code="\033["
  case "$1" in
    black  | bk) color="${code}0;30m";;
    red    |  r) color="${code}1;31m";;
    green  |  g) color="${code}1;32m";;
    yellow |  y) color="${code}1;33m";;
    blue   |  b) color="${code}1;34m";;
    purple |  p) color="${code}1;35m";;
    cyan   |  c) color="${code}1;36m";;
    gray   | gr) color="${code}0;37m";;
    *) local text="$1"
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  printf "$text"
}

DIR="/dev/dysk"

if [ $# -eq 2  ]; then
	if [ $1="-n" ]; then
		cecho c "=========================> Mounting $2...\n"
		echo "Mounting $2..."
		sudo mkdir -p $DIR 
		sudo mount -t ntfs-3g /dev/$2 $DIR
		cecho c "=========================> Mounted\n"
	fi
elif [ $# -eq 1  ]; then
	cecho c "=========================> Mounting $1...\n"
	sudo mkdir -p $DIR 
	sudo mount /dev/$1 $DIR
	cecho c "=========================> Mounted\n"
else
	echo "You did something wrong."
	echo "Please read this help:"
	echo
	echo "m -n sdxX          mount ntfs device"
	echo "m sdxX             mount other device"
	echo "um"                umount mounted device
fi
