#!/bin/bash

# using command "um" you can easily umount device from destination dir 

cecho() {
  local code="\033["
  case "$1" in
    black  | bk) color="${code}0;30m";;
    red    |  r) color="${code}1;31m";;
    green  |  g) color="${code}1;32m";;
    yellow |  y) color="${code}1;33m";;
    blue   |  b) color="${code}1;34m";;
    purple |  p) color="${code}1;35m";;
    cyan   |  c) color="${code}1;36m";;
    gray   | gr) color="${code}0;37m";;
    *) local text="$1"
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  printf "$text"
}

# destination dir
DIR="/dev/dysk"

if [ -d $DIR  ] # if dir exist
	then
		if [ "$(ls -A $DIR)"  ] # if dir isn't empty
			then
                cecho c "=========================> Unmounting $DIR...\n"
                cd $HOME
				sudo umount $DIR 
                cecho c "=========================> Done\n"
			else
				cecho r "$DIR is empty\n"
		fi
	else
		echo $DIR does not exist.
fi

