#!/bin/bash

# using command "um" you can easily umount device
# e.g. um

DIR="/dev/dysk"

# if dir exists
if [ -d $DIR  ]; then
	# if dir isn't empty
	if [ "$(ls -A $DIR)"  ]; then 
		echo Unmounting /dev/dysk...
                cd /home/michal
		sudo umount $DIR 
        if [ "$?" -eq "0" ]; then
            cecho c "=========================> Unmounted correctly\n"
        else
            cecho r "=========================> ERROR\n"
        fi
	else
		echo "$DIR is empty"
	fi
else
	echo $DIR does not exist.
fi

