(setq custom-file "~/.emacs.d/src/custom.el")
;;(load custom-file)
(load-file "~/.emacs.d/src/repositories.el")
(load-file "~/.emacs.d/src/packages.el")
(load-file "~/.emacs.d/src/interface.el")
(load-file "~/.emacs.d/src/binds.el")
